# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d6b98189530fde5a04673eb69f56320763eb09d023d95f9c951f2cf6c6e75c292a788cf9c8d6ad9b4803efebed0fcc35002326822e63f56024efa5c06e9ef3

test:
  secret_key_base: e1fc85b2a8afd5da627938d4bcb706bfe041736637bcd545ebe94bc4b9cacea72e8810650ece4ba68c3dfaf6ab7f4c28951b0dc3e1956ff38849eaba516b3534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
